### ISSUE TITLE
Rainbow carpets from Earth2Java don't stack, but waste carpets

### ISSUE THREAD

**Issue by SplendidAlakey** [RacoonDog/carpet-layers#2]
**MC** 1.19.2
**QFAPI** 4.0.0-beta.24
**[Earth2Java](https://www.curseforge.com/minecraft/mc-mods/earth2java-fabric)** 1.9.3
**Carpet Layers** 1.0.1

To reproduce grab a stack of rainbow carpets, start placing them down on top of each other and observe, that while carpets do get taken from you, they don't stack and get voided.

Interestingly, if you waste enough carpets, it will place 1 on top, as if you placed a full block of carpets:

![2022-12-14_00 58 05](https://user-images.githubusercontent.com/86702831/207471199-f62375e0-7858-4aa2-a040-8bbd455a559c.png)

Logs: https://gist.github.com/SplendidAlakey/a1bb7a29b5347bcc6563f1ed3ed51970

**Comment by crosby-moe** [comment]
> **MC** 1.19.2 **QFAPI** 4.0.0-beta.24 **[Earth2Java](https://www.curseforge.com/minecraft/mc-mods/earth2java-fabric)** 1.9.3 **Carpet Layers** 1.0.1
> 
> To reproduce grab a stack of rainbow carpets, start placing them down on top of each other and observe, that while carpets do get taken from you, they don't stack and get voided.
> 
> Interestingly, if you waste enough carpets, it will place 1 on top, as if you placed a full block of carpets:
> 
> ![2022-12-14_00 58 05](https://user-images.githubusercontent.com/86702831/207471199-f62375e0-7858-4aa2-a040-8bbd455a559c.png)
> 
> Logs: https://gist.github.com/SplendidAlakey/a1bb7a29b5347bcc6563f1ed3ed51970

working *as intended*, in the sense that all carpets have the functionality added, but only the vanilla ones have models defined

i *could* dynamically generate model files for all carpets, but it wouldn't work all the times, in particular with this case where the textures would not line up correctly

unfortunately this case would only be resolved via premade texture, which is outside of the scope of this project as i want to keep it lightweight

**Comment by SplendidAlakey** [comment]
That's a bummer. Wouldn't it make sense in that case to restrict stacking to vanilla carpets only? If at all possible.

**Comment by crosby-moe** [comment]
> That's a bummer. Wouldn't it make sense in that case to restrict stacking to vanilla carpets only? If at all possible.

yes, yes it would

**Comment by crosby-moe** [comment]
> That's a bummer. Wouldn't it make sense in that case to restrict stacking to vanilla carpets only? If at all possible.

Here are the various ways I could implement this:
- Only make vanilla carpets stackable.
- Only make vanilla carpets stackable, with a way for mod authors to opt-in.
- Only make vanilla carpets stackable, with a way for the player to enable some via configs.
- Make all carpets stackable.
- Make all carpets stackable, with a way for mod authors to opt-out.
- Make all carpets stackable, with a way for the player to disable some via configs.

**Comment by SplendidAlakey** [comment]
In my opinion, the best way is to

- Only make vanilla carpets stackable, with a way for mod authors to opt-in

Because if we leave it up to players to enable in configs, then there's still a problem of missing textures/models. And making everything stackable by default leads to my initial issue.

So I'd say, option 2 is the best, option 1 will also work.

**Comment by crosby-moe** [comment]
> In my opinion, the best way is to
> 
> * Only make vanilla carpets stackable, with a way for mod authors to opt-in
> 
> Because if we leave it up to players to enable in configs, then there's still a problem of missing textures/models. And making everything stackable by default leads to my initial issue.
> 
> So I'd say, option 2 is the best, option 1 will also work.

I can fairly easily circumvent the missing textures/models issue, though if I add a way to opt-in for mod authors, I don't think many people will actually use it

**Comment by SplendidAlakey** [comment]
I was under the impression, that it's not possible? According to your comment above. But if you can make it compatible out of the box with any modded carpets, then sure, that would be ideal.

**Comment by crosby-moe** [comment]
> I was under the impression, that it's not possible? According to your comment above. But if you can make it compatible out of the box with any modded carpets, then sure, that would be ideal.

I can dynamically generate models rather easily, but one of the cases where it wouldn't work is with `Earth2Java`.
Since this specific carpet model doesn't have the same UV mapping on every side of the block, if it were to be stacked using the regular UV mappings, it would look something like [this](https://imgur.com/a/U5q4azC).

**Comment by SplendidAlakey** [comment]
Ah, I see. So then I think it would be best to have only vanilla carpets stack by default and have a config option to turn on modded carpets stacking. That way, people who enable the option should be aware of potential issues.

**Comment by crosby-moe** [comment]
> Ah, I see. So then I think it would be best to have only vanilla carpets stack by default and have a config option to turn on modded carpets stacking. That way, people who enable the option should be aware of potential issues.

Oh I hadn't thought of that. (Plus that way I can add a way for the user to remove carpets that don't work if they do activate it.)

**Comment by crosby-moe** [comment]
found a working compromise in 1.1.0

basically had to remove stacking for modded carpets altogether
sadge, but couldnt find any other options
